### ISSUE TITLE
Analytics API Integration

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#101]
#### General Information

This section will provide information on what resources where used by each student, how long have they been browsing on those pages, which videos were watched and what was the duration of that. 
The information will be gather using our Analytics Chrome Extension which is going to be enabled in all Chromebooks of the students.
#### API Documentation

To get API documentation please download this file https://www.dropbox.com/s/ytle8hishqb92d9/swagger.txt?dl=0 copy all contents from it and paste into the left section here - http://editor.swagger.io/#/

ROOT API URL: https://analytics-staging.learningtapestry.com/api/v2

Keys for the EASOL project:
org_api_key=51bb257c-c40a-4f51-bdb6-2ba697bb6167
org_secret_key=35d433acef73eb67bf4db5f0b68f3baca6b0
#### Tasks
- [x] 1. Add sub-menu level support for "Learning Lab". 
- [x] 2. Create hashing mechanism for student emails 
- [x] 3. View: All Sections 
- [x] 4. View: All Students in a Section
- [x] 5. VIew: Single Student
##### 1. Add sub-menu level support for "Learning Lab".

The same thing like with "Management" has to be done. Once tapping on a Learning Tapestry we should see two buttons
a) "Content search" - we already have this
b) "Analytics" - this is what is going to be developed in this task.
##### 2. Create hashing mechanism for student emails

Since we need to keep some level of Privacy in our API, we don't save pure email value in our database - it is getting hashed.
Hashing algorithm to be used **bcrypt**. Below is the description from Analytics API developer. Please follow it to get the same hash for the email, so we could match those against the ones coming from the API. Once the algorithm is ready - inform @edgarf to test it with the hashes saved.

"Since we can't rely on a random salt generation because email hashes should always remain the same for a given email, what I do is compute the salt by generating a SHA-256 digest from the same email plus the base content url (ie: http://easol-dev.azurewebsites.net), and then taking the first 22 characters in base64 format (that's what bcrypt expects as salt). "

_Here's a small example:_

> Given the email `user@example.org` and the content url `http://easol-dev.azurewebsites.net`, the generated salt would be `$2a$10$OTRiMmI0ZTYyZDRhYTZjNT` (the last 22 characters come from the calculated SHA-256 hash using email + content url).
> 
> Applying then the bcrypt algorithm with this salt, the resulting hash would be `$2a$10$OTRiMmI0ZTYyZDRhYTZjNO.dlLosUR7MyMj/R3C.7gmuE5piVJmMe`
##### 3. View: All Sections

**Layout**
Mockup for this view: http://easol-dev.azurewebsites.net/phaseii/index.html#p=analytics 
Basically, it's the same view like in "Section" (the one which was "Grades" before). We have all sections listed down. Before getting into the details about Analytics part, a few changes should be done to the list view itself - all data/column shoul be the same as it is now in "Sections" (the menu item which used to be called "Grades"), just the "grade information" will be empty (analytics will be there instead). Additionally, column "Assignments" can be removed, since we can't yet calculate this value.
Filter at the moment is not yet required, however - we might add it in the future, so it's good to have it in mind.

**Analytics** 
To get the analytics data you see in the prototype, you have to get data about all of the students from each section and count average online time. 
_However_ - we can't take all browsing data from the user, so before calling the API, time intervals when each section is happening should be found. 
The Data Model of "Bell Schedule" and its relation to Sections can be found here https://techdocs.ed-fi.org/display/EFDS20/Bell+Schedule+-+UDM+v2.0

`/sites` function can be used for this.
Firstly, find all students and hash their data and pass it to ``usernames` attribute separated by a comma. Then you will need to call this function for every bell schedule interval - you can only apply 1 date interval for now (_we might update it later to decrease number of calls_)
##### 4. View: All Students in a Section

**Layout**
Mockup for this view: http://easol-dev.azurewebsites.net/phaseii/index.html#p=analytics-students
As you can see it's the same view we get when open details of a section in "Section" menu item (the one which used to be "Grades").
Assignment column can be removed.
**Analytics**

`/pages` function can be used for "Pages Visited" and "Total Time Online". The difference between `/pages` and `/sites` is that the second one only provides the domains and the first one exact pages. Since we need to get the information only about a single user each time, only 1 hashed `username` will be provided. However, the number of calls will be the same, since we need to use the same time intervals for the exact section

`/video-views` - can be used for "Videos Watched" and "Total Time - Videos" - `username` and date interval params would be the same like using the `/pages` above.
##### 5. VIew: Single Student

**Important** - This view should have 2 variables in the URL - Student and Section ID. This is required because the same student can have different analytics activity with different Sections
**Layout**
The prototype is not yet there. However, for now it's giong to be a simple "Browsing history view".
A table with 3 columns: 1) "Date-time" 2) URL 3) Time spent.

There should be an indication of the Student (full name) and Section Data (the same like in Section Detail view)  at the begining

**Analytics**
All functions from above should be used. Using the hashed email of current student and all of the intervals for the exact section.
