### ISSUE TITLE
Add "Section" detail view in "Grade" menu section

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#98]
The "Grades" section provides a list of all sections, courses. We need to provide an ability to tap on a "Section name" and see some detailed information.

**Tasks in Grades menu item**
- [x] 1. Add a link on "Section Name" columns to get Section detail view screen
- [x] 2. Trim "Period" column value.
- [x] 3. Add "Grade Level" column
- [x] 4. Add "Term" column
- [x] 5. Integrate "Section Detail view" screen
- [x] 6. Remove current "Sections" menu item and rename "Grades"
#### 2.  Trim "Period" column value.

Only leave the numerical value of this column, all string value should be removed.
For example:
`01 - Traditional` should be converted to `01`
#### 3. Add "Grade Level" column

Each Section has "Grade Level" attribute. The way to get the value can be found analyzing how the "Sections" section gets it in the "Course Name" string.  
#### 4. Add "Term" column

Each Section has "Term" attribute. The way to get the value can be found analyzing how the "Sections" section gets it in the "Term" column.  
#### 5. Integrate "Section Detail view" screen

There should be a heading of the page saying "Section: {Section Unique Number}".  Then a small information about the section meta-data has to be provided: 
Educator : {Educator full name}
Grade Level: {Grade level}
Term: {Term}
Period: {Period}.
Below, a list of students should be listed with ability to click on a student and get on a Student Detail view (this view already exists - only a redirect there is needed).
For now a list with students will only have 1 column "Student Full Name". Further, there will be more columns - so it's worth putting a proper table.

All database queries can be found in existing code.
#### 6. Remove current "Sections" menu item and rename "Grades"

It's probably noticed, that "Grades" and "Sections" menu items are very similar with the content. This is why we need to remove one of those. Since all of the changes in this ticket were provided for the "Grades" section, let's a) Remove current "Sections" menu item b) Rename current "Grades" to "Sections" (it would be good if we could rename the controller too)
